package com.lqminhlab.mm_travel.src.resource.models

data class AttractionModel(
    val address: String? = "",
    val address_obj: AddressObj? = AddressObj(),
    val ancestors: List<Ancestor>? = listOf(),
    val animal_welfare_tag: AnimalWelfareTag? = AnimalWelfareTag(),
    val awards: List<Award>? = listOf(),
    val bearing: Any? = Any(),
    val booking: Booking? = Booking(),
    val category: Category? = Category(),
    val description: String? = "",
    val distance: Any? = Any(),
    val distance_string: Any? = Any(),
    val doubleclick_zone: String? = "",
    val email: String? = "",
    val fee: String? = "",
    val hours: Hours? = Hours(),
    val is_candidate_for_contact_info_suppression: Boolean? = false,
    val is_closed: Boolean? = false,
    val is_jfy_enabled: Boolean? = false,
    val is_long_closed: Boolean? = false,
    val latitude: String? = "",
    val location_id: String? = "",
    val location_string: String? = "",
    val location_subtype: String? = "",
    val longitude: String? = "",
    val name: String? = "",
    val nearest_metro_station: List<Any>? = listOf(),
    val neighborhood_info: List<NeighborhoodInfo>? = listOf(),
    val num_reviews: String? = "",
    val offer_group: OfferGroup? = OfferGroup(),
    val open_now_text: String? = "",
    val parent_display_name: String? = "",
    val phone: String? = "",
    val photo: Photo? = Photo(),
    val preferred_map_engine: String? = "",
    val ranking: String? = "",
    val ranking_category: String? = "",
    val ranking_denominator: String? = "",
    val ranking_geo: String? = "",
    val ranking_geo_id: String? = "",
    val ranking_position: String? = "",
    val ranking_subcategory: String? = "",
    val rating: String? = "",
    val raw_ranking: String? = "",
    val shopping_type: String? = "",
    val subcategory: List<SubcategoryX>? = listOf(),
    val subcategory_ranking: String? = "",
    val subtype: List<Subtype>? = listOf(),
    val ta_message: TaMessage? = TaMessage(),
    val tags: Tags? = Tags(),
    val timezone: String? = "",
    val web_url: String? = "",
    val website: String? = "",
    val write_review: String? = ""
) {
    fun toLocation(): LocationModel {
        return LocationModel(
            listOf(),
            listOf(),
            "",
            "",
            "",
            "",
            "",
            "",
            false,
            false,
            false,
            false,
            "",
            "",
            "",
            "",
            "",
            listOf(),
            listOf(),
            "",
            photo!!,
            "",
            listOf(),
            "",
            "",
            this
        )
    }
}